Backup
olr-fh/ITOPS-Studienarbeit pull request #3
Opened 2024-06-04 12:24 UTC by schlechtOptimiziert

2024-06-09 16:33 UTC, olr-fh requested changes
Review  bis jetzt vergessen ups

2024-06-09 16:33 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +Um den Speicherverbrauch zu veringern kann man auch die Veränderungen seit dem letzten Full Backup speichern. Dieses Diff Backup ist dennoch langsam beim Einspielen, da alle Diff Backups auf das letz
```suggestion
Um den Speicherverbrauch zu veringern kann man auch die Veränderungen seit dem letzten Full Backup speichern. Dieses Diff Backup ist jedoch langsam beim Einspielen, da alle Diff Backups auf das letzte Full Backup angewandt werden müssen.
```

2024-06-09 16:33 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +Um die Vor- und Nachteile von Diff und Full Backup auszuschöpfen, werden beide Techniken verwendet. Jede Woche wird ein Full Backup erstellt, zudem wird Täglich ein Diff Backup erstellt. Nach einem M
```suggestion
Um die Vor- und Nachteile von Diff und Full Backup auszuschöpfen, werden beide Techniken verwendet. Jede Woche wird ein Full Backup erstellt, zudem wird Täglich ein Diff Backup erstellt. Nach einem Monat wird das letzte Backup als monatliches Full Backup gespeichert und die anderen Wöchentlichen werden gelöscht.
```

2024-06-09 16:33 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +Wichtige Daten sind Source Code und Applikationsdatein, welche nötig sind, um in Notfall die Applikation wieder zum laufen zu bringen. Applikationsdatein sollten in einem möglichst hohen Intervall ge
```suggestion
Wichtige Daten sind Source Code und Applikationsdateien, welche nötig sind, um im Notfall die Applikation wieder zum laufen zu bringen. Applikationsdateien sollten in einem möglichst hohen Intervall gesichert werden, um den Verlust von Nutzerdaten zu unterbinden. Stündlich werden diese Daten, inform eines diffs, gesichert.
```

2024-06-09 16:33 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +Das Speichern der Backups geschied auf zwei Servern in unterschiedlichen Datacentern. Diese beinhalten jewails alle Daten, sind also voll replizierend. Die Server selber arbeiten mit mehreren Speiche
```suggestion
Das Speichern der Backups geschied auf zwei Servern in unterschiedlichen Datacentern. Diese beinhalten jeweils alle Daten, sind also voll replizierend. Die Server selber arbeiten mit mehreren Speichermedien auf denen eine Raid 6 Replikation stattfindet.\newline
```

2024-06-09 16:33 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +Raid 6 ist eine Technik, bei welcher die Daten vor dem Ausfallen von einem bis zwei Speichermedien schützt. Auch das Austauschen von Speichermedien kann einfach durch das Wechseln eines Datenträgers
```suggestion
Raid 6 ist eine Technik, bei welcher die Daten vor dem Ausfallen von einem bis zwei Speichermedien geschützt sind. Auch das Austauschen von Speichermedien kann einfach durch das Wechseln eines Datenträgers geschehen. Durch die selbstheilende Fähigkeit wird der neue Datenträger automatisch mit den Daten beschrieben.\newline
```

2024-06-09 16:33 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +Somit sind die Daten innerhalb eines Datencenters vor Ausfällen einer oder mehrere Festplatten gesichert. Auch  Auch vor größeren Vorfällen, wie einem Brand in einem Datacenter, sind die Daten geschü
```suggestion
Somit sind die Daten innerhalb eines Datencenters vor Ausfällen einer oder mehrere Festplatten gesichert. Auch vor größeren Vorfällen, wie einem Brand in einem Datacenter, sind die Daten geschützt. (Vgl. \cref{fig:BackupStrategie})
```

2024-06-09 17:17 UTC, olr-fh commented on chapter/Backupstrategie.tex
> +\section{Backupstrategie}
```suggestion
\section{Backupstrategie (Dominik und Oliver)}
```

2024-06-09 20:17 UTC, schlechtOptimiziert commented on chapter/Backupstrategie.tex
> +\section{Backupstrategie}
Also das verstehe ich jetzt nicht so ganz, wie wir das mit zwei Namen machen. Bei Amelie und dir hat man dann noch die Untersektionen beschrieben, aber hier hat man fast keine und wenn würde an allen mein Name stehen. Zudem weiß ich nicht, ob du das nicht gesehen hattest oder was, aber deinen Teil hatte ich komplett entfernt. Das einzige, was davon noch zurrückgeblieben ist, ist halt inhaltlicher Gedanke.
Mit anderen Worten ist dein Beitrag nicht in Text zu sehen.

Meinentwegen kann dein Name da auch stehen, aber wie das jetzt ist geht der Umfang deines und meines Anteils nicht so heraus. Da muss man sich für ne Lösung überlegen.

![image](https://github.com/olr-fh/ITOPS-Studienarbeit/assets/107460536/b71ed061-cce6-4372-a76b-7d0e233adb2c)

2024-06-10 08:35 UTC, olr-fh approved these changes
jaja

2024-06-10 08:35 UTC, merged