Add Plan
olr-fh/ITOPS-Studienarbeit pull request #5
Opened 2024-06-10 08:07 UTC by schlechtOptimiziert

2024-06-10 08:08 UTC, schlechtOptimiziert commented
Unter Plan sind noch Sections auf der selben Ebene wie die Prozess section. Dass muss eigendlich auf eine 4-te Ebene. Aber LaTex lässt das so nicht zu.

2024-06-10 09:55 UTC, olr-fh requested changes
einige sachen

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +\todo[inline]{Wertstrom behandeln}
ich denke mal "\todo[inline]{Wertstrom behandeln}" kann weg

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +In der Planungsphase legt das Produktmanagement zunächst das Projektziel fest und bestimmt dann die erforderlichen Ressourcen und Pläne, um das Ziel zu erreichen.\footnote{https://t2informatik.de/wis
```suggestion
In der Planungsphase legt das Produktmanagement zunächst das Projektziel fest und bestimmt dann die erforderlichen Ressourcen und Pläne, um das Ziel zu erreichen.\footnote{https://t2informatik.de/wissen-kompakt/devops. Abgerufen am 03. Juni 2024.} Das Management teilt dann das Projekt den Entwicklungsteams zu und legt die Werkzeuge, das Budget und den Zeitplan fest. Für unser Unternehmen wird das Scrum-Framework, ein agiles Projektmanagemet-Framework ausgewählt. Dabei besteht die Softwareentwicklung aus einem Scrum Master, einem Product Owner und Entwicklern.
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
>  \subsubsection{Prozesse}
Ich glaube diese Section kann komplett weg, dann haben wir das Problem mit den zu tiefen sections nicht. Ansonsten gibts auch wege das mit \paragraph umzusetzen (https://tex.stackexchange.com/questions/60209/how-to-add-an-extra-level-of-sections-with-headings-below-subsubsection)

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Sobald das Ziel und die Ressourcen festgelegt sind, werden die Anforderungen der Stakeholder (Kunden) vom Produktmanagement gesammelt und dem Product Owner in einem Meeting mitgeteilt, der sie mithil
```suggestion
Sobald das Ziel und die Ressourcen festgelegt sind, werden die Anforderungen der Stakeholder (Kunden) vom Produktmanagement gesammelt und dem Product Owner in einem Meeting mitgeteilt, der sie mithilfe von dem Scrum-Master in einem Aufgabenmanagement-Tool erfasst. Diese werden dann in einem Produkt-Backlog \cref{fig:ScrumFramework} gespeichert und verwaltet, die aller noch zu erledigenden Aufgaben darstellt. Diese Aufgaben werden zuerst aufgelistet, wobei die wichtigsten Aufgaben ganz oben auf der Liste stehen. Dabei teilt das Produktmanagement der Softwareentwicklung nicht mit, wie es arbeiten soll oder Sprints plant. Teams haben dann Autonomie, wie die Aufgaben ausgeführt werden, jedoch muss diese Ausführung mit den Zielen des Managements übereinstimmen.\footnote{https://learn.microsoft.com/de-de/devops/plan/scaling-agile. Abgerufen am 05. Juni 2024.}
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Diese Phase wird in zweiwöchigen Scrum-Sprints von dem Scrum-Master organisiert, die auf der \cref{fig:ScrumFramework} zu sehen. Dieser sorgt nicht nur dafür, Scrum-Events zu moderieren, sondern auch
```suggestion
Diese Phase wird in zweiwöchigen Scrum-Sprints von dem Scrum-Master organisiert, wie auf \cref{fig:ScrumFramework} zu sehen. Dieser sorgt nicht nur dafür, Scrum-Events zu moderieren, sondern auch, dass Teams effektiv und effizient arbeiten, dabei unterstützt er die Integration von DevSecOps-Praktiken, damit eine nahtlose Zusammenarbeit zwischen den Teams gewähleistet wird.
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Jeden Morgen während des Sprints gibt es ein tägliches Meeting (Daily), in dem die Teilnehmer kurze Updates geben, was sie am Vortag gemacht haben und was sie am nächsten Tag machen wollen. Hindernis
```suggestion
Jeden Morgen während des Sprints gibt es ein tägliches Meeting (Daily), in dem die Teilnehmer kurze Updates geben, was sie am Vortag gemacht haben und was sie am nächsten Tag machen wollen. Hindernisse und Probleme werden dabei sofort besprochen und Lösungen werden gemeinsam erarbeitet. Am Ende des Sprints sollte ein potenziell auslieferbares Produktinkrement entstanden sein. Daher kommunizieren Teams mit den Stakeholdern, um deren Bedürfnisse herauszufinden und sie über die neuesten Entwicklungen des Projekts auf dem Laufenden zu halten. Es folgt ein Sprint Review und ein Retrospective Meeting, bei dem die bisherigen Sprint-Arbeiten und -Ergebnisse präsentiert und Verbesserungsmöglichkeiten identifiziert werden. Dieses Feedback fließt in die Planung des nächsten Sprints ein.\footnote{https://www.scrum.org/learning-series/what-is-scrum/the-scrum-events/what-is-sprint-planning. Abgerufen am 03 Juni 2024.}
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Für ein gut funktionierendes Produkt achtet BlümchenHub darauf, Risiken frühzeitig zu verwalten und zu minimieren. Diese Risiken können sowohl technischer als auch Prozessbezogene sein. Beispielsweis
```suggestion
Für ein gut funktionierendes Produkt achtet BlümchenHub darauf, Risiken frühzeitig zu verwalten und zu minimieren. Diese Risiken können sowohl technische als auch Prozessbezogene sein. Beispielsweise können fehlerhafte Implementierungen zu Systemausfällen oder kritischen Bugs führen, die den Aufwand erhöhen. Auch eine schlechte Kommunikation zwischen den Teams kann zu Missverständnissen über die Anforderungen und damit zu Fehlentwicklungen führen. Fehlende Ressourcen durch Krankheit oder Abwesenheit von Mitarbeitern können dazu führen, dass Termine nicht eingehalten werden können, was wiederum zu erhöhten Kosten führt.\newline
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +In unserem Unternehmen wird Jira verwendet, um Aufgaben zu erstellen und den Fortschritt bei der Entwicklung neuer Features für die BlümchenHub2.0-Website zu überwachen und sicherzustellen, dass alle
```suggestion
In unserem Unternehmen wird Jira verwendet, um Aufgaben zu erstellen und den Fortschritt bei der Entwicklung neuer Features für die BlümchenHub2.0-Website zu überwachen und sicherzustellen, dass alle Teams effektiv zusammenarbeiten.
```
würde ich weglassen, wir gründen ja kein neues Unternehmen, das sollte schon da sein.

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Ein Hauptelement in Jira sind sogenannte '"Issues'", die viele Formen annehmen können. Diese sind auf der \cref{fig:JiraIssues} zu sehen: Epic, Bug, Story, Sub-Task, Task.\newline
```suggestion
Ein Hauptelement in Jira sind sogenannte "`Issues"', die viele Formen annehmen können. Diese sind auf der \cref{fig:JiraIssues} zu sehen: Epic, Bug, Story, Sub-Task, Task.\newline
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Am Ende jedes Sprints werden Sprint Reports (\cref{fig:JiraSprintReport}) erstellt, die den Fortschritt und die Leistung der Teams in textueller und graphischer Darstellung aufzeigen. Sie enthalten d
```suggestion
Am Ende jedes Sprints werden Sprint Reports (\cref{fig:JiraSprintReport}) erstellt, die den Fortschritt und die Leistung der Teams in textueller und graphischer Darstellung aufzeigen. Sie enthalten das Sprint-Ziel und Ergebnisse und zeigen welche Aufgaben wurden abgeschlossen und welche nicht. Sie dienen dazu, Verbesserungsmöglichkeiten für zukünftige Sprints zu identifizieren.\newline
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Cycle.tex
> +Velocity Charts (\cref{fig:JiraVelocityReport}) werden über mehrere Sprints hinweg erstellt und verwendet, um die durchschnittliche Leistung als graphische Darstellung zu bestimmen, die Teams in eine
```suggestion
Velocity Charts (\cref{fig:JiraVelocityReport}) werden über mehrere Sprints hinweg erstellt und verwendet, um die durchschnittliche Leistung als graphische Darstellung zu bestimmen, die Teams in einem Sprint erreichen können und um die Abarbeitungsgeschwindigkeit des Backlogs abzuschätzen. Dies ist besonders nützlich für zukünftige realistische Planung und hilft den Teams zu verstehen, wie viel Arbeit sie in einem Sprint erledigen können. 
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Kundenfeedback.tex
> +Unser Unternehmen BlümchenHub ist ihm ganz wichtig, ihr Kunden zufrieden zu stellen. Dafür braucht unsere Softwareentwicklung zu verstehen was den Kunden gefällt und was nicht, deswegen ist es wichti
```suggestion
Für unser Unternehmen BlümchenHub ist es wichtig, Kunden zufrieden zu stellen. Dafür muss unsere Softwareentwicklung verstehen was den Kunden gefällt und was nicht, deswegen ist es wichtig Feedback zu holen, um Bedürfnisse der Kunden berücksichtigen zu können.\newline
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Kundenfeedback.tex
> +Kundenfeedback sind Meinungen von Kunden nach ihrer Erfahrung mit einem Produkt, dies kann sowohl negativ als auch positiv sein. Das Sammeln von diesen Feedbacks hat eine große Priorität in BlümchenH
```suggestion
Kundenfeedback sind Meinungen von Kunden nach ihrer Erfahrung mit einem Produkt, dies kann sowohl negativ als auch positiv sein. Das Sammeln von diesen Feedback hat eine große Priorität in BlümchenHub, da dies zu einer kontinuierlichen Verbesserung des Unternehmens und zur Analyse der Marktleistung führen kann.\footnote{Megha Adityan (2023). Warum Kundenfeedback wichtig ist. https://www.vtiger.com/de/blog/why-customer-feedback-is-important. Abgerufen am 08. Juni 2024.}
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Kundenfeedback.tex
> +Feedback kann auch zwischen Mitarbeitern und Teams gesammelt werden. Dadurch können Probleme und Fehler während der Entwicklung schnell erkannt und behoben werden, um den Endbenutzern qualitativ hoch
```suggestion
Feedback kann auch von den Mitarbeitern und den Teams gesammelt werden. Dadurch können Probleme und Fehler während der Entwicklung schnell erkannt und behoben werden, um den Endbenutzern qualitativ hochwertige Software zu liefern. Um dies zu erreichen, können beispielsweise automatisierte Tests durchgeführt werden, indem während des gesamten Zyklus kontinuierlich Tests ausgeführt werden und gegebenenfalls Fehlermeldungen zurückgegeben werden, die dann behoben werden können. Darüber hinaus könnten Entwickler ihre Implementierungen untereinander austauschen und Code-Reviews erhalten, die Verbesserungsvorschläge machen können.
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Kundenfeedback.tex
> +Damit Zeit und Aufwand gespart wird, wird Jira Issue Collector benutzt für die Sammlung der Kundenfeedbacks. Dies ist wie auf der \cref{fig:JiraFeedbackFormular} zu sehen in Form eines Buttons der ge
```suggestion
Damit Zeit und Aufwand gespart wird, wird der Jira Issue Collector benutzt, für die Sammlung der Kundenfeedbacks. Dies ist wie auf der \cref{fig:JiraFeedbackFormular} zu sehen in Form eines Buttons der gedrückt wird, damit das Formular angezeigt wird. So können alle Besucher der Website einfach ihr Feedback geben, ohne ein Jira-Konto zu haben. Sobald das Formular abgeschickt wird, erstellt Jira direkt ein Issue im Backlog.
```

2024-06-10 09:55 UTC, olr-fh commented on chapter/Kundenfeedback.tex
> +In Jira am Beispiel der \cref{fig:JiraIssueCollectorErstellen} wird zuerst ein Issue Collector erstellt, dies ist also Feedback gennant und enthält Fragen, die zu den Kunden gestellt werden. Danach w
```suggestion
In Jira am Beispiel der \cref{fig:JiraIssueCollectorErstellen} wird zuerst ein Issue Collector erstellt, dies wird ein Feedback gennant und enthält Fragen, die den Kunden gestellt werden. Danach wird eine Seite mit Codeschnipseln angezeigt., was verwendet wird, um den Issue Collector in der Website einzubinden.\footnote{https://support.atlassian.com/jira-cloud-administratio/docs/use-the-issue-collector. Abgerufen am 08. Juni 2024.}
```

2024-06-10 10:35 UTC, schlechtOptimiziert commented on chapter/Cycle.tex
> +In unserem Unternehmen wird Jira verwendet, um Aufgaben zu erstellen und den Fortschritt bei der Entwicklung neuer Features für die BlümchenHub2.0-Website zu überwachen und sicherzustellen, dass alle
Ja, aber wir nutzen neu Jiar. YK

2024-06-11 13:50 UTC, olr-fh commented on chapter/Cycle.tex
>  \subsubsection{Prozesse}
Die gemeinte Section ist "\subsubsection{Prozesse}"

2024-06-13 14:20 UTC, olr-fh approved these changes

2024-06-13 14:21 UTC, merged